
import { GoogleGenAI, Type } from "@google/genai";
import { AdCopy, FormState, GroundingSource } from '../types';

// Always use process.env.API_KEY as per guidelines
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const adSchema = {
    type: Type.OBJECT,
    properties: {
        headline: {
          type: Type.STRING,
          description: "A compelling, short headline for this specific ad.",
        },
        body: {
          type: Type.STRING,
          description: "The main body text for this ad, contributing to the overall story.",
        },
    },
    required: ['headline', 'body'],
};

const responseSchema = {
  type: Type.OBJECT,
  properties: {
    positiveEmotions: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "An array of 2-3 single-word or short-phrase positive emotions found in online sentiment analysis.",
    },
    negativeEmotions: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "An array of 2-3 common complaints or negative emotions found in reviews.",
    },
    campaign: {
        type: Type.ARRAY,
        description: "A series of exactly 3 interconnected ads that tell a cohesive, concise story.",
        items: adSchema,
    }
  },
  required: ['campaign'],
};

export const generateAdCopy = async (formState: FormState): Promise<AdCopy> => {
  const { brandName, platform, goal, tone } = formState;

  const isNegativeAnalysis = goal === 'Address Customer Concerns';

  const systemInstruction = `You are an expert marketing analyst and copywriter operating an "Emotional Resonance Ad Engine".
  Your task is to analyze real-world online sentiment for a brand using the Google Search tool and generate an emotionally resonant, story-driven ad campaign.

  Workflow:
  1. Search for real user reviews, news, and feedback about "${brandName}".
  2. Identify key emotional patterns.
  3. Generate a 3-part campaign:
     - If goal is "${goal}": 
       ${isNegativeAnalysis 
         ? 'Ad 1: Acknowledge the pain point. Ad 2: Introduce the solution. Ad 3: Show the better future.' 
         : 'Ad 1: Establish the emotional connection. Ad 2: Deepen the narrative. Ad 3: Drive the final call to action.'}
  
  Constraints:
  - Target Platform: ${platform}
  - Tone: ${tone}
  - Goal: ${goal}
  - Number of ads: exactly 3.`;

  const prompt = `Analyze the brand/product "${brandName}" and provide the emotional analysis and 3-part ad campaign as specified.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        systemInstruction,
        tools: [{googleSearch: {}}],
        responseMimeType: "application/json",
        responseSchema: responseSchema,
      },
    });

    // Extract grounding sources from groundingMetadata
    const groundingMetadata = response.candidates?.[0]?.groundingMetadata;
    const sources: GroundingSource[] = [];
    
    if (groundingMetadata?.groundingChunks) {
      groundingMetadata.groundingChunks.forEach(chunk => {
        if (chunk.web && chunk.web.uri) {
          sources.push({
            uri: chunk.web.uri,
            title: chunk.web.title || 'Source',
          });
        }
      });
    }

    // De-duplicate sources
    const uniqueSources = Array.from(new Map(sources.map(s => [s.uri, s])).values());

    // Safely extract text before parsing
    const text = response.text;
    if (!text) {
      throw new Error("No analysis data was generated by the model.");
    }

    const parsedResponse: AdCopy = JSON.parse(text);
    
    return { ...parsedResponse, sources: uniqueSources };

  } catch (error) {
    console.error("Error calling Gemini API:", error);
    // Fix: Ensure error.message access is safe and correctly logical
    if (error instanceof Error && (error.message.includes("404") || error.message.includes("not found"))) {
        throw new Error("Analysis failed: The model configuration or API endpoint was not found. Please verify your connection.");
    }
    throw new Error("Failed to generate ad copy. Our engine encountered an issue during analysis.");
  }
};
