
import React, { useState } from 'react';
import { AdCopy } from '../types';

interface AdCopyDisplayProps {
  adCopy: AdCopy;
  brandName: string;
}

const AdCopyDisplay: React.FC<AdCopyDisplayProps> = ({ adCopy, brandName }) => {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const hasPositiveEmotions = adCopy.positiveEmotions && adCopy.positiveEmotions.length > 0;
  const hasNegativeEmotions = adCopy.negativeEmotions && adCopy.negativeEmotions.length > 0;
  const hasSources = adCopy.sources && adCopy.sources.length > 0;
  const hasCampaign = adCopy.campaign && adCopy.campaign.length > 0;

  const handleCopy = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const handleDownloadHTML = () => {
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ad Campaign - ${brandName}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; background-color: #f4f7f6; }
        h1 { color: #1e1b4b; border-bottom: 2px solid #4f46e5; padding-bottom: 10px; }
        .section { background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .label { font-size: 0.8rem; font-weight: bold; text-transform: uppercase; color: #4f46e5; margin-bottom: 8px; display: block; }
        .tag { display: inline-block; background: #e0e7ff; color: #4338ca; padding: 4px 12px; border-radius: 999px; font-size: 0.9rem; margin-right: 8px; margin-bottom: 8px; font-weight: 500; }
        .tag-neg { background: #fef3c7; color: #92400e; }
        .ad-card { border-left: 4px solid #4f46e5; padding-left: 20px; margin-bottom: 30px; }
        .ad-title { font-weight: bold; font-size: 1.2rem; color: #1e1b4b; margin-bottom: 8px; }
        .ad-body { white-space: pre-wrap; color: #4b5563; }
        .footer { font-size: 0.8rem; color: #9ca3af; text-align: center; margin-top: 40px; }
        a { color: #4f46e5; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>Campaign Strategy: ${brandName}</h1>
    
    <div class="section">
        <span class="label">Positive Emotional Resonance</span>
        <div>${adCopy.positiveEmotions?.map(e => `<span class="tag">${e}</span>`).join('') || 'N/A'}</div>
        
        <br>
        
        <span class="label">Customer Concerns</span>
        <div>${adCopy.negativeEmotions?.map(e => `<span class="tag tag-neg">${e}</span>`).join('') || 'N/A'}</div>
    </div>

    <div class="section">
        <span class="label">The Campaign</span>
        ${adCopy.campaign.map((ad, i) => `
            <div class="ad-card">
                <div class="ad-title">Ad ${i + 1}: ${ad.headline}</div>
                <div class="ad-body">${ad.body}</div>
            </div>
        `).join('')}
    </div>

    ${hasSources ? `
    <div class="section">
        <span class="label">Analysis Sources</span>
        <ul>
            ${adCopy.sources?.map(s => `<li><a href="${s.uri}">${s.title || s.uri}</a></li>`).join('')}
        </ul>
    </div>
    ` : ''}

    <div class="footer">Generated by Emotional Resonance Ad Engine • Powered by Gemini</div>
</body>
</html>`;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `campaign-${brandName.toLowerCase().replace(/\s+/g, '-')}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900/50 backdrop-blur-sm p-6 md:p-8 rounded-2xl shadow-2xl border border-indigo-800 space-y-6">
      {hasPositiveEmotions && (
        <div>
          <h2 className="text-sm font-semibold text-indigo-400 uppercase tracking-wider mb-2">Positive Emotional Resonance</h2>
          <div className="flex flex-wrap gap-2">
            {adCopy.positiveEmotions?.map((emotion, index) => (
              <span key={index} className="bg-indigo-500/20 text-indigo-300 text-sm font-medium px-3 py-1 rounded-full">
                {emotion}
              </span>
            ))}
          </div>
        </div>
      )}

      {hasNegativeEmotions && (
        <div>
          <h2 className="text-sm font-semibold text-amber-400 uppercase tracking-wider mb-2">Common Customer Concerns</h2>
          <div className="flex flex-wrap gap-2">
            {adCopy.negativeEmotions?.map((emotion, index) => (
              <span key={index} className="bg-amber-500/20 text-amber-300 text-sm font-medium px-3 py-1 rounded-full">
                {emotion}
              </span>
            ))}
          </div>
        </div>
      )}
      
      {(hasPositiveEmotions || hasNegativeEmotions) && <div className="border-t border-indigo-800"></div>}

      <div>
        <h2 className="text-sm font-semibold text-indigo-400 uppercase tracking-wider mb-3">Generated Ad Campaign</h2>
        <div className="space-y-6">
          {hasCampaign && adCopy.campaign.map((ad, index) => (
            <div key={index} className="bg-indigo-950/50 p-5 rounded-xl border border-indigo-800 relative group">
               <button 
                 onClick={() => handleCopy(`${ad.headline}\n\n${ad.body}`, index)}
                 className="absolute top-4 right-4 p-2 text-indigo-400 hover:text-white hover:bg-indigo-800/50 rounded-lg transition-all"
                 title="Copy to clipboard"
               >
                 {copiedIndex === index ? (
                   <span className="text-xs font-bold text-green-400">Copied!</span>
                 ) : (
                   <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                     <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                   </svg>
                 )}
               </button>
               <h3 className="font-bold text-lg text-white mb-2 pr-16">
                <span className="text-indigo-400 font-semibold">Ad {index + 1}:</span> {ad.headline}
               </h3>
               <p className="text-gray-300 whitespace-pre-wrap">{ad.body}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="pt-4 flex flex-col md:flex-row gap-4">
        <button 
          onClick={handleDownloadHTML}
          className="flex-1 flex items-center justify-center gap-2 bg-indigo-600/20 hover:bg-indigo-600/40 text-indigo-300 font-semibold py-3 px-6 rounded-xl border border-indigo-600/50 transition-all"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download Campaign (.html)
        </button>
      </div>

      {hasSources && (
         <>
            <div className="border-t border-indigo-800"></div>
            <div>
                <h2 className="text-sm font-semibold text-indigo-400 uppercase tracking-wider mb-2">Sources</h2>
                <ul className="space-y-2">
                    {adCopy.sources?.map((source, index) => (
                        <li key={index} className="truncate">
                            <a 
                                href={source.uri} 
                                target="_blank" 
                                rel="noopener noreferrer"
                                className="text-indigo-300 hover:text-indigo-200 hover:underline transition-colors duration-200 text-sm"
                            >
                                {source.title || source.uri}
                            </a>
                        </li>
                    ))}
                </ul>
            </div>
         </>
      )}
    </div>
  );
};

export default AdCopyDisplay;
